export const LANGUAGE_MAP: Record<string, string> = {
	ar: "Arabic",
	am: "Amharic",
	bg: "Bulgarian",
	bn: "Bengali",
	ca: "Catalan",
	cs: "Czech",
	da: "Danish",
	de: "German",
	el: "Greek",
	en: "English",
	"en-AU": "English (Australia)",
	"en-GB": "English (Great Britain)",
	"en-US": "English (USA)",
	es: "Spanish",
	"es-419": "Spanish (Latin America and Caribbean)",
	et: "Estonian",
	fa: "Persian",
	fi: "Finnish",
	fil: "Filipino",
	fr: "French",
	gu: "Gujarati",
	he: "Hebrew",
	hi: "Hindi",
	hr: "Croatian",
	hu: "Hungarian",
	id: "Indonesian",
	it: "Italian",
	ja: "Japanese",
	kn: "Kannada",
	ko: "Korean",
	lt: "Lithuanian",
	lv: "Latvian",
	ml: "Malayalam",
	mr: "Marathi",
	ms: "Malay",
	nl: "Dutch",
	no: "Norwegian",
	pl: "Polish",
	"pt-BR": "Portuguese (Brazil)",
	"pt-PT": "Portuguese (Portugal)",
	ro: "Romanian",
	ru: "Russian",
	sk: "Slovak",
	sl: "Slovenian",
	sr: "Serbian",
	sv: "Swedish",
	sw: "Swahili",
	ta: "Tamil",
	te: "Telugu",
	th: "Thai",
	tr: "Turkish",
	uk: "Ukrainian",
	vi: "Vietnamese",
	"zh-CN": "Chinese (China)",
	"zh-TW": "Chinese (Taiwan)",
};
