export const PATHS = {
	root: "/",
	error: "/error",
	login: "/login",
	kakaoLogin: "/accounts.kakao.com",
	googleLogin: "/accounts.google.com",
	memos: "/memos",
	auth: "/auth",
	introduce: "/introduce",
	update: "/update",
	memosWish: "/memos?isWish=true",
	memosSetting: "/memos/setting",
	callbackOAuth: "/auth/callback",
	callbackEmail: "/auth/callback-email",
	admin: "/admin",
	adminUsers: "/admin/users",
	featuresYoutubeSummary: "/features/youtube-summary",
	featuresMemo: "/features/memo",
	featuresSaveArticles: "/features/save-articles",
	useCasesResearch: "/use-cases/research",
	useCasesLearning: "/use-cases/learning",
	useCasesJobHunting: "/use-cases/job-hunting",
	useCasesNewsReading: "/use-cases/news-reading",
	useCasesYoutubeNotes: "/use-cases/youtube-notes",
	useCasesDeveloper: "/use-cases/developer",
	useCasesTechArticle: "/use-cases/tech-article",
};

export const NEED_AUTH_PAGES = [
	PATHS.memos,
	PATHS.memosWish,
	PATHS.memosSetting,
	PATHS.admin,
	PATHS.adminUsers,
];
