export const STORAGE_OPTION_LANGUAGE = 'LANGUAGE';
export const STORAGE_OPTION_MEMO_STORAGE = 'MEMO_STORAGE';
export const STORAGE_OPTION_LIST = [STORAGE_OPTION_LANGUAGE, STORAGE_OPTION_MEMO_STORAGE];
