export const STORAGE_TYPE_OPTION_LANGUAGE = 'LANGUAGE';
export const STORAGE_TYPE_OPTION_MEMO_STORAGE = 'MEMO_STORAGE';
export const STORAGE_TYPE_OPTION_LIST = [STORAGE_TYPE_OPTION_LANGUAGE, STORAGE_TYPE_OPTION_MEMO_STORAGE];
