export const BRIDGE_MESSAGE_TYPES = {
	GET_EXTENSION_MANIFEST: "GET_EXTENSION_MANIFEST",
	GET_SIDE_PANEL_OPEN: "GET_SIDE_PANEL_OPEN",
	OPEN_SIDE_PANEL: "OPEN_SIDE_PANEL",
	GET_SUMMARY: "GET_SUMMARY",
	GET_TABS: "GET_TABS",
	PAGE_CONTENT: "PAGE_CONTENT",
	YOUTUBE_TRANSCRIPT: "YOUTUBE_TRANSCRIPT",
	REFETCH_THE_MEMO_LIST_FROM_WEB: "REFETCH_THE_MEMO_LIST_FROM_WEB",
	REFETCH_THE_MEMO_LIST_FROM_EXTENSION: "REFETCH_THE_MEMO_LIST_FROM_EXTENSION",
	UPDATE_SIDE_PANEL: "UPDATE_SIDE_PANEL",
	SYNC_LOGIN_STATUS: "SYNC_LOGIN_STATUS",
	CREATE_MEMO: "CREATE_MEMO",
} as const;

export type Category = "youtube" | "others";
