export const BRIDGE_MESSAGE_TYPES = {
  GET_EXTENSION_MANIFEST: 'GET_EXTENSION_MANIFEST',
  GET_SIDE_PANEL_OPEN: 'GET_SIDE_PANEL_OPEN',
  OPEN_SIDE_PANEL: 'OPEN_SIDE_PANEL',
  GET_SUMMARY: 'GET_SUMMARY',
  GET_TABS: 'GET_TABS',
  PAGE_CONTENT: 'PAGE_CONTENT',
  REFETCH_THE_MEMO_LIST: 'REFETCH_THE_MEMO_LIST',
  UPDATE_SIDE_PANEL: 'UPDATE_SIDE_PANEL',
} as const;

export type Category = 'youtube' | 'others';
