export const BLOG_LOGO_BASE_URL = "https://tech-mail.shop/blogs/";

export interface TechBlog {
  name: string;
  url: string;
  logo: string;
}

export const TECH_BLOGS: TechBlog[] = [
  { name: "토스", url: "https://toss.tech/", logo: "toss.ico" },
  { name: "네이버 D2", url: "https://d2.naver.com/", logo: "naver.png" },
  { name: "카카오", url: "https://tech.kakao.com/blog", logo: "kakao.png" },
  { name: "우아한형제들", url: "https://techblog.woowahan.com/", logo: "woowahan.png" },
  { name: "당근마켓", url: "https://medium.com/daangn", logo: "daangn.ico" },
  { name: "라인", url: "https://engineering.linecorp.com/", logo: "line.ico" },
  { name: "무신사", url: "https://medium.com/musinsa-tech", logo: "musinsa.ico" },
  { name: "마켓컬리", url: "https://helloworld.kurly.com/", logo: "kurly.png" },
  { name: "인프랩", url: "https://tech.inflab.com/", logo: "inflab.png" },
  { name: "카카오페이", url: "https://tech.kakaopay.com/", logo: "kakaopay.png" },
  { name: "올리브영", url: "https://oliveyoung.tech/blog/", logo: "oliveyoung.png" },
  { name: "29cm", url: "https://medium.com/29cm", logo: "29cm.png" },
  { name: "뱅크샐러드", url: "https://blog.banksalad.com/", logo: "banksalad.ico" },
  { name: "여기어때", url: "https://techblog.gccompany.co.kr/", logo: "goodchoice.png" },
  { name: "요기요", url: "https://techblog.yogiyo.co.kr/", logo: "yogiyo.svg" },
  { name: "네이버 DnA", url: "https://medium.com/naver-dna-tech-blog", logo: "naver.png" },
  { name: "네이버 페이", url: "https://medium.com/naverfinancial", logo: "naver-pay.jpeg" },
  { name: "카카오엔터FE", url: "https://fe-developers.kakaoent.com/", logo: "kakao-entertainment.png" },
  { name: "카카오헤어샵", url: "https://brunch.co.kr/@purpledev", logo: "kakao-hairshop.jpeg" },
  { name: "직방", url: "https://medium.com/zigbang", logo: "zigbang.ico" },
  { name: "AWS", url: "https://aws.amazon.com/ko/blogs", logo: "aws.jpeg" },
  { name: "한글과컴퓨터", url: "https://tech.hancom.com/", logo: "hancom.png" },
  { name: "가비아", url: "https://library.gabia.com/", logo: "gabia.png" },
  { name: "딜라이트룸", url: "https://medium.com/delightroom", logo: "delightroom.jpeg" },
  { name: "인포그랩", url: "https://insight.infograb.net/blog", logo: "infograb.jpeg" },
  { name: "SSG.COM", url: "https://medium.com/ssgtech", logo: "ssgcom.png" },
  { name: "NHN", url: "https://meetup.nhncloud.com/", logo: "nhn.jpeg" },
  { name: "데브시스터즈", url: "https://tech.devsisters.com/", logo: "devsisters.png" },
  { name: "교보DTS", url: "https://blog.kyobodts.co.kr/", logo: "kyobo.jpeg" },
  { name: "SK플래닛", url: "https://techtopic.skplanet.com/", logo: "sk-planet.jpeg" },
  { name: "마이리얼트립", url: "https://medium.com/myrealtrip-product/", logo: "myrealtrip.ico" },
  { name: "뤼이드", url: "https://medium.com/riiid-teamblog-kr", logo: "riiid.png" },
  { name: "크리에이트립", url: "https://medium.com/creatrip", logo: "creatrip.png" },
  { name: "하이퍼커넥트", url: "https://hyperconnect.github.io/", logo: "hyperconnect.png" },
  { name: "쏘카", url: "https://tech.socarcorp.kr/", logo: "socar.png" },
  { name: "마키나락스", url: "https://www.makinarocks.ai/category/tech", logo: "makinarocks.jpeg" },
  { name: "농심NDS", url: "https://tech.cloud.nongshim.co.kr", logo: "nongshim-nds.png" },
  { name: "베스핀글로벌", url: "https://blog.bespinglobal.com/", logo: "bespin-global.png" },
  { name: "11번가", url: "https://11st-tech.github.io/", logo: "11st.png" },
  { name: "크림", url: "https://medium.com/kream-%EA%B8%B0%EC%88%A0-%EB%B8%94%EB%A1%9C%EA%B7%B8", logo: "kream.png" },
  { name: "watcha", url: "https://medium.com/watcha", logo: "watcha.ico" },
  { name: "캐치테이블", url: "https://medium.com/catchtable", logo: "catchtable.png" },
  { name: "포스타입", url: "https://www.postype.com/@team", logo: "postype.png" },
  { name: "비브로스", url: "https://boostbrothers.github.io/", logo: "bbros.png" },
  { name: "매스프레소", url: "https://blog.mathpresso.com/", logo: "mathpresso.jpeg" },
  { name: "펫프렌즈", url: "https://techblog.pet-friends.co.kr", logo: "petfriends.jpeg" },
  { name: "현대자동차", url: "https://developers.hyundaimotorgroup.com/blog", logo: "hyundai.png" },
  { name: "토니모리", url: "https://tonymoly-tech.medium.com/", logo: "tonymoly.png" },
  { name: "spoqa", url: "https://spoqa.github.io/", logo: "spoqa.png" },
  { name: "리멤버", url: "https://tech.remember.co.kr/", logo: "remember.png" },
  { name: "컴투스", url: "https://on.com2us.com/", logo: "com2us.jpeg" },
  { name: "RIDI", url: "https://ridicorp.com/story-category/tech-blog/", logo: "ridi.png" },
  { name: "모두싸인", url: "https://team.modusign.co.kr/", logo: "modusign.png" },
  { name: "롯데ON", url: "https://techblog.lotteon.com/", logo: "lotte-on.jpeg" },
  { name: "카테노이드", url: "https://techblog.catenoid.net/", logo: "catenoid.jpeg" },
  { name: "지마켓", url: "https://ebay-korea.tistory.com/", logo: "gmarket.ico" },
  { name: "직행", url: "https://zighang.inblog.ai/", logo: "zighang.jpeg" },
  { name: "테이블링", url: "https://medium.com/tabling-tech", logo: "tabling.webp" },
  { name: "다나와", url: "https://danawalab.github.io/", logo: "danawa.ico" },
  { name: "CJ온스타일", url: "https://medium.com/cj-onstyle", logo: "cj-onstyle.jpeg" },
  { name: "8퍼센트", url: "https://8percent.github.io/", logo: "8percent.jpeg" },
  { name: "메가존클라우드", url: "https://medium.com/ctc-mzc", logo: "mgazone-cloud.png" },
  { name: "넷마블", url: "https://netmarble.engineering/", logo: "netmarble.jpg" },
  { name: "사람인", url: "https://saramin.github.io/", logo: "saramin.jpeg" },
  { name: "빅웨이브AI", url: "https://bigwaveai.tistory.com/", logo: "bigwave.png" },
  { name: "씨앤텍", url: "https://cntechsystems.tistory.com/", logo: "cntechsystems.jpeg" },
  { name: "엘리시아", url: "https://medium.com/elysia-techblog", logo: "elysia.png" },
  { name: "아이디어스", url: "https://medium.com/idus-tech", logo: "idus.png" },
  { name: "IMQA", url: "https://blog.imqa.io/tag/tech", logo: "imqa.png" },
  { name: "딜리셔스", url: "https://dealicious-inc.github.io/", logo: "dealiciou.svg" },
  { name: "NC DANBI", url: "https://danbi-ncsoft.github.io/", logo: "ncsoft-danbi.png" },
  { name: "TechKi", url: "https://air77.hashnode.dev/", logo: "air77.png" },
];

export const QUICK_ACCESS_COUNT = 15;
