name: Build And Upload Extension Zip Via Artifact

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Create .env
        run: |
          echo VITE_OPENAI_API_KEY=${{ secrets.VITE_OPENAI_API_KEY }} >> .env
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - run: pnpm install --frozen-lockfile --prefer-offline

      - run: pnpm build

      - uses: actions/upload-artifact@v4
        with:
          name: zip-artifact
          path: dist/*
          if-no-files-found: error
